---
title: "Lecture Schedule - Fall 2022"
permalink: /docs/
output:
  html_document:
    df_print: paged
excerpt: Class Schedule
redirect_from: "/theme-setup/"
last_modified_at: "2022-08-18"
---

Each module will have an assignment associated that could be a simple quiz, a reflection piece or solving a LP model in R, Python or Excel. The readings associated with each module will be posted on Sakai. The proposed schedule below is subject to change. My initial plan is to cover all the material listed here but I might modify it if extra time is needed for some particular topics. I will provide updates via Sakai or Slack.

Note that we may have classes during energy week if there is a session or panel related to the topics discussed in class. If that's the case, you are supposed to attend the session in lieu of the class. And you are expected to write about it in your journal.

| Week | Module | Date | Topic | Assignment |
|----|----|------|-----------------------------|----|
| 1 | 1 | Aug 29 - 31 | Introductions, Review of Electric Power Systems: Generator, Transmission, Distribution, Load, "Old" Grids and Its Problems, The Solution: Smart Grid , Introduction to Smart Grids or Modern Power Grids: Definition, Benefits, Opportunities and Challenges | J1 |
| 2 | 2 | Sep 5 - 7 | Smart Grid from Global Perspective: How electricity distribution will change? ICT Perspectives, Smart-meter deployment, End user view, DSO view, AMI deployment experience Vermont and Sweden |J2 |
| 3 | 3 | Sep 12 - 14 | Smart Grid from Global Perspective: How generation will change, paradigm shift, renewable energy sources, challenges of renewable resource integration, Distributed Generation: definition, history, planning and operation |J3 |
| 4 | 4 | Sep 19 - 21 | Rooftop PV study case, Solar Penetration Outlook, The Duck Curve and Possible Solutions | A1 |
| 5 | 5 | Sep 26 - 28 | Distributed Generation: challenges of DG integration, location, power quality and stability | J4 |
| 6 | 6 | Oct 3 - 5 | DER: Energy Storage Applications to Power Systems, Intro to LP in R using "lpsolveAPI" package | A2 |
| 7 | 6 | Oct 10 - 12 | Fall break, we will use the class on Wed to work on assignment and/or project | A3 |
| 8 | - | Oct 17 - 19 | Energy Storage Management, Residential PV+battery, Residential PV+battery study case: problem formulation  | J5 |
| 9 | 7 | Oct 24 - 26 | Impact of DER on grid operation/scheduling and planning, ED problem with Renewables, Case study - Hydro-thermal scheduling Brazil | J6 |
| 10 | 8 | Oct 31 - Nov 2 | Intro to Network Pricing, Economics of Transmission and Distribution Network Pricing, Revenue Requirement (CAPEX + OPEX), OPEX - Utility benchmark analysis, Data Envelopment Analysis | J7 |
| 11 | 9 | Nov 7 - 9 | Energy Week - no classes - use that time to attend events and work on project | A4 |
| 12 | 9 | Nov 21  | Distribution Use of System Charges: Cost Allocation Part I - Principles and Assumptions & Cost Allocation Part II - Fixed cost methods, DC Power Flow | J8 |
| 13 | - | Nov 28 - 30 | Distribution Use of System Charges Cost Allocation Part III - Case Study - Part IV - Incremental/Marginal cost methods, Final Project Presentations | A5 |



